##### inventory.yaml #####
## Inventory Settings ##
# limitedByWeight: {bool} 
  # should the inventory be limited by the weight of it's items
# weightCapacity: {float} 
  # the maximum amount of weight this inventory can hold
limitedByWeight: false
weightCapacity: 0