##### itemDatabase.yaml #####
# This file contains the data of all items in the game.
# Each item is defined in their corresponding item category (named after an Item Subclass).

## General Settings ##
# extractSpriteData: {bool} 
  # should the game extract all internal sprites to "<game_folder>/gamedata/sprites/items/" on start?
  # extracted sprites do NOT overwrite existing sprites
extractSpriteData: false

## Item Categories ##
# Entries in item categories use the following format:
# <ItemClass>:
#   categoryName:<string> # the in-game name of this item category>
#   items:
#     <itemEntry>:       # unique identifier for this item  
#       <key>:<value>     # parameters used on this class of item
#       ...
#     ...

# When a parameter in an item is not defined, the game loads it's default value instead
# Parameters used in all items:
# name: {string, default="generic_item"} # the in-game name of the item
# cost: {int, default=0}                 # the item's base cost (> 0)
# weight: {float, default=0}             # the item's weight
# stackLimit: {int, default=99}          # maximum number of this item in a stack (> 0)         
# multiStack: {bool, default=true}       # allow additional stacks in inventory?
# spritePath: {string, default="<itemEntry>.png"} 
  # path to the item's sprite, relative to "<game_folder>/gamedata/sprites/items/"
  # supported sprite formats are: .bmp, .exr, .gif, .hdr, .iff, .jpg, .pict, .png, .psd, .tga and .tiff

## Weapons ##
# Parameters used in Weapons:
# attack: {int, default=0} # this weapon's attack value
Weapon:
  categoryName: "Weapons"
  items:
    ShortSword:
      name: "Short Sword"
      cost: 50
      attack: 3
      weight: 3.5
    MagicSword:
      name: "Magic Sword"
      cost: 400
      attack: 9
      weight: 5.8
## Armors ##
# Parameters used in Armors:
# defense: {int, default=0} # this armor's defense value
Armor:
  categoryName: "Armors"
  items:
    LeatherTunic:
      name: "Leather Tunic"
      cost: 30
      defense: 1
      weight: 4.2
## Key Items ##
KeyItem:
  categoryName: "Key Items"
  items:
    BookOfKnowledge:
      name: "Book of Knowledge"
      stackLimit: 1
      multiStack: false
    TrianglePiece:
      name: "Triangle Piece"
      stackLimit: 3
      multiStack: false
