##### equipment.yaml #####
## Equipment Settings ##
# these define the slots in which items can be equipped
# each slot has the following parameters:
# name: {string}
  # the in-game name of the item slot
# itemType: {string}
  # what <ItemClass> can be equipped in this slot (see itemDatabase.yaml)
  # use "Item" for the slot to work with any item (since it's the base class for all items)
equipmentSlots:
  Torso:
    name: "Torso"
    itemType: Armor
  LeftHand:
    name: "Left Hand"
    itemType: Weapon
  RightHand:
    name: "Right Hand"
    itemType: Item