##### inventory.yaml #####
# This file contains configuration data for the player's inventory.

# Parameters used in inventory.yaml:
# limitedByWeight: {bool, default=false} 
  # should the inventory be limited by the weight of it's items
# weightCapacity: {float, default=0} 
  # the maximum amount of weight this inventory can hold

limitedByWeight: false
weightCapacity: 0

## Equipment Slots ##
# these define the slots in which items can be equipped
# each slot has the following parameters:
# name: {string}
  # the in-game name of the item slot
# itemType: {string}
  # what <ItemClass> can be equipped in this slot (see itemDatabase.yaml)

equipmentSlots:
  Torso:
    name: "Torso"
    itemType: "Armor"
  Hands:
    name: "Hands"
    itemType: "Weapon"